# Generated by Django 4.1.4 on 2022-12-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='agents/')),
                ('facebook', models.TextField()),
                ('twitter', models.TextField()),
                ('instagram', models.TextField()),
                ('google', models.TextField()),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.agentposition')),
            ],
        ),
        migrations.CreateModel(
            name='AboutRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_requirements', to='home.about')),
            ],
        ),
    ]
