# Generated by Django 4.1.4 on 2022-12-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_agent_facebook_alter_agent_google_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='home.agentposition'),
        ),
    ]
