# Generated by Django 4.1.4 on 2022-12-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_agent_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='instagram',
            new_name='linkedin',
        ),
    ]
