# Generated by Django 4.1.4 on 2022-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_have_community_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property/video'),
        ),
    ]
